import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

const API = 'http://127.0.0.1:8000/api'
type View = 'dashboard' | 'profile' | 'resume' | 'skillgap' | 'roadmap' | 'practice' | 'interview' | 'projects' | 'feedback'
type Profile = { college?: string; degree?: string; branch?: string; current_year?: number; graduation_year?: number; target_role?: string; experience_level?: string; technical_skills: string[]; weekly_study_time?: number; learning_preference?: string }
type Summary = { profile_complete: boolean; target_role?: string; skills_recorded: number; resume_uploaded: boolean; resume_score?: number; readiness_score?: number | null; missing_skills?: string[] }
type Resume = { id: number; filename: string; skills: string[]; score: number; created_at?: string }
type Gap = { target_role: string; required_skills: string[]; matching_skills: string[]; missing_skills: string[]; readiness_score: number }
type Roadmap = { target_role: string; weeks: number; based_on_missing_skills: string[]; roadmap: { week: number; goal: string; topics: string[]; tasks: string[]; estimated_hours: number; milestone: string }[] }
type Question = { id: string; topic: string; difficulty: string; type: string; question: string; options: string[] }
type Project = { name: string; difficulty: string; skills_learned: string[]; problem_statement: string; steps: string[] }
type Feedback = { overall_readiness: number; strong_areas: string[]; weak_areas: string[]; immediate_actions: string[]; next_milestone: string }

async function request<T>(path: string, method = 'GET', body?: object): Promise<T> {
  const token = localStorage.getItem('careerai_token')
  const response = await fetch(API + path, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: body ? JSON.stringify(body) : undefined })
  const data = await response.json().catch(() => null)
  if (!response.ok) throw new Error(data?.detail || data?.error?.message || 'Request failed')
  return data as T
}

async function uploadResume(file: File): Promise<Resume> {
  const token = localStorage.getItem('careerai_token'); const formData = new FormData(); formData.append('file', file)
  const response = await fetch(`${API}/auth/resume/upload`, { method: 'POST', headers: token ? { Authorization: `Bearer ${token}` } : {}, body: formData })
  const data = await response.json().catch(() => null)
  if (!response.ok) throw new Error(data?.detail || 'Resume upload failed')
  return data as Resume
}

const nav: { label: string; value: View; icon: string }[] = [
  { label: 'Dashboard', value: 'dashboard', icon: '⌂' }, { label: 'My profile', value: 'profile', icon: '◉' }, { label: 'Resume analysis', value: 'resume', icon: '▤' }, { label: 'Skill gap', value: 'skillgap', icon: '◌' }, { label: 'Roadmap', value: 'roadmap', icon: '↗' }, { label: 'Practice', value: 'practice', icon: '✦' }, { label: 'Mock interview', value: 'interview', icon: '◐' }, { label: 'Projects', value: 'projects', icon: '▱' }, { label: 'Feedback', value: 'feedback', icon: '♡' },
]
const Chip = ({ children, tone = '' }: { children: React.ReactNode; tone?: string }) => <span className={`chip ${tone}`}>{children}</span>
const Meter = ({ value }: { value: number }) => <div className="meter"><i style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>
const Empty = ({ text }: { text: string }) => <div className="empty">{text}</div>

function Auth({ onReady }: { onReady: () => void }) {
  const [register, setRegister] = useState(false); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setLoading(true); setMessage(''); try { const body: Record<string, unknown> = { email: form.get('email'), password: form.get('password') }; if (register) body.name = form.get('name'); const result = await request<{ access_token: string }>(`/auth/${register ? 'register' : 'login'}`, 'POST', body); localStorage.setItem('careerai_token', result.access_token); onReady() } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to continue') } finally { setLoading(false) } }
  return <main className="auth"><div className="brand">CareerAI <b>Mentor</b></div><p className="tag">Your placement preparation command center</p><h1>{register ? 'Create your account' : 'Welcome back'}</h1><p>Turn your next career move into a focused plan.</p><form onSubmit={submit}>{register && <input required name="name" placeholder="Your full name" />}<input required name="email" type="email" placeholder="Email address" /><input required name="password" type="password" minLength={8} placeholder="Password" /><button disabled={loading}>{loading ? 'Please wait…' : register ? 'Create account' : 'Sign in'}</button></form>{message && <p className="notice error">{message}</p>}<button className="text-button" onClick={() => setRegister(!register)}>{register ? 'Already have an account? Sign in' : 'New student? Create an account'}</button></main>
}

function App() {
  const [ready, setReady] = useState(!!localStorage.getItem('careerai_token')); const [view, setView] = useState<View>('dashboard'); const [profile, setProfile] = useState<Profile | null>(null); const [summary, setSummary] = useState<Summary | null>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false)
  const [resumes, setResumes] = useState<Resume[]>([]); const [gap, setGap] = useState<Gap | null>(null); const [roadmap, setRoadmap] = useState<Roadmap | null>(null); const [checked, setChecked] = useState<number[]>([]); const [questions, setQuestions] = useState<Question[]>([]); const [answers, setAnswers] = useState<Record<string, string>>({}); const [practiceResults, setPracticeResults] = useState<Record<string, { correct: boolean; explanation: string }>>({}); const [interview, setInterview] = useState<{ type: string; target_role: string; question: string } | null>(null); const [interviewFeedback, setInterviewFeedback] = useState<{ overall_score: number; communication_score: number; feedback: string } | null>(null); const [projects, setProjects] = useState<Project[]>([]); const [feedback, setFeedback] = useState<Feedback | null>(null); const [today, setToday] = useState<{ priority: number; action: string; minutes: number }[]>([])
  const notify = (error: unknown, fallback: string) => setMessage(error instanceof Error ? error.message : fallback)
  const loadBase = async () => { const [nextProfile, nextSummary] = await Promise.all([request<Profile | null>('/auth/profile'), request<Summary>('/auth/dashboard/summary')]); setProfile(nextProfile); setSummary(nextSummary) }
  useEffect(() => { if (!ready) return; loadBase().catch(() => { localStorage.removeItem('careerai_token'); setReady(false) }) }, [ready])
  function show(next: View) { setView(next); setMessage('') }
  async function action(work: () => Promise<void>) { setLoading(true); setMessage(''); try { await work() } catch (error) { notify(error, 'Something went wrong') } finally { setLoading(false) } }
  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await action(async () => { const saved = await request<Profile>('/auth/onboarding', 'PUT', { college: form.get('college') || null, degree: form.get('degree') || null, branch: form.get('branch') || null, current_year: Number(form.get('current_year')) || null, graduation_year: Number(form.get('graduation_year')) || null, target_role: form.get('target_role') || null, experience_level: form.get('experience_level') || null, technical_skills: String(form.get('technical_skills')).split(',').map(s => s.trim()).filter(Boolean), weekly_study_time: Number(form.get('weekly_study_time')) || null, learning_preference: form.get('learning_preference') || null }); setProfile(saved); await loadBase(); setMessage('Profile saved. Your workspace is ready to personalize.') }) }
  async function loadResumes() { await action(async () => setResumes(await request<Resume[]>('/auth/resume'))) }
  async function handleResume(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const file = new FormData(event.currentTarget).get('file'); if (!(file instanceof File) || !file.size) return setMessage('Choose a TXT resume file first.'); await action(async () => { const uploaded = await uploadResume(file); setResumes(old => [uploaded, ...old.filter(item => item.id !== uploaded.id)]); await loadBase(); setMessage('Resume analyzed successfully.') }) }
  if (!ready) return <Auth onReady={() => setReady(true)} />
  const readiness = summary?.readiness_score ?? 0
  return <div className="shell"><aside><div className="brand">CareerAI <b>Mentor</b></div><p className="aside-label">PREP WORKSPACE</p>{nav.map(item => <button key={item.value} className={view === item.value ? 'active' : ''} onClick={() => show(item.value)}><i>{item.icon}</i>{item.label}</button>)}<button className="logout" onClick={() => { localStorage.removeItem('careerai_token'); setReady(false) }}>Log out</button></aside><section className="content">{loading && <div className="loading">Updating your workspace…</div>}{message && <p className="notice">{message}</p>}
    {view === 'dashboard' && <><header className="hero"><div><p className="eyebrow">CAREER PREPARATION</p><h1>{profile?.target_role || 'Build your career plan'}</h1><p>{profile?.college ? `${profile.college} · ${profile.degree || 'Student'}` : 'Complete your profile and take your first focused step.'}</p></div><button className="light" onClick={() => show('profile')}>Edit profile</button></header><div className="stat-grid"><article><strong>{summary?.skills_recorded || 0}</strong><span>skills recorded</span></article><article><strong>{summary?.resume_uploaded ? `${summary.resume_score}%` : '—'}</strong><span>resume score</span></article><article><strong>{summary?.readiness_score ?? '—'}{summary?.readiness_score != null && '%'}</strong><span>role readiness</span></article></div><div className="two-col"><article className="panel"><div className="section-head"><div><p className="eyebrow">READINESS</p><h2>Your role match</h2></div><strong>{readiness}%</strong></div><Meter value={readiness} /><p>{summary?.missing_skills?.length ? `Focus next on ${summary.missing_skills.slice(0, 2).join(' and ')}.` : 'Choose a target role to see a personalized match.'}</p><button onClick={() => show('skillgap')}>View skill gap</button></article><article className="panel"><p className="eyebrow">NEXT STEP</p><h2>Keep the momentum</h2><p>{summary?.resume_uploaded ? 'Use your latest resume to generate a skill-gap report and roadmap.' : 'Upload a TXT resume to add another signal to your plan.'}</p><button onClick={() => show(summary?.resume_uploaded ? 'skillgap' : 'resume')}>{summary?.resume_uploaded ? 'Analyze skill gap' : 'Upload resume'}</button></article></div></>}
    {view === 'profile' && <><PageTitle title="Student profile" text="Tell us where you are now and where you want to go." /><form className="grid panel" onSubmit={saveProfile}><input name="college" defaultValue={profile?.college || ''} placeholder="College" /><input name="degree" defaultValue={profile?.degree || ''} placeholder="Degree" /><input name="branch" defaultValue={profile?.branch || ''} placeholder="Branch / specialization" /><input name="current_year" type="number" defaultValue={profile?.current_year || ''} placeholder="Current year" /><input name="graduation_year" type="number" defaultValue={profile?.graduation_year || ''} placeholder="Graduation year" /><select name="target_role" defaultValue={profile?.target_role || ''}><option value="">Target career role</option>{['AI Engineer','Python Developer','Data Analyst','Data Scientist','ML Engineer','Full Stack Developer'].map(role => <option key={role}>{role}</option>)}</select><select name="experience_level" defaultValue={profile?.experience_level || ''}><option value="">Experience level</option>{['Beginner','Intermediate','Advanced'].map(level => <option key={level}>{level}</option>)}</select><input name="technical_skills" defaultValue={profile?.technical_skills?.join(', ') || ''} placeholder="Skills: Python, SQL, Git" /><input name="weekly_study_time" type="number" defaultValue={profile?.weekly_study_time || ''} placeholder="Weekly study hours" /><input name="learning_preference" defaultValue={profile?.learning_preference || ''} placeholder="Learning preference" /><button>Save profile</button></form></>}
    {view === 'resume' && <><PageTitle title="Resume analysis" text="Upload a PDF, Word, or TXT resume to identify skills and calculate your resume score." /><form className="upload panel" onSubmit={handleResume}><div><strong>Drop in your resume</strong><p>PDF, Word (.docx), or TXT files — up to 5 MB.</p></div><input name="file" type="file" accept=".txt,.pdf,.docx,text/plain,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" /><button>Upload & analyze</button></form><div className="section-head"><h2>Your resume history</h2><button className="secondary" onClick={loadResumes}>Refresh</button></div>{resumes.length ? <div className="card-grid">{resumes.map(resume => <article className="panel resume-card" key={resume.id}><div className="section-head"><strong>{resume.filename}</strong><div className="resume-score" aria-label={`Resume score ${resume.score} out of 100`}><span>Resume score</span><b>{resume.score}%</b></div></div><Meter value={resume.score} /><p className="muted">Recognized skills</p><div className="chips">{resume.skills.length ? resume.skills.map(skill => <Chip key={skill}>{skill}</Chip>) : <span>None recognized yet</span>}</div></article>)}</div> : <Empty text="No resumes loaded yet. Upload one or choose Refresh to see your history." />}</>}
    {view === 'skillgap' && <><PageTitle title="Skill-gap analysis" text="Compare your profile and latest resume with your target role." /><button onClick={() => action(async () => { setGap(await request<Gap>('/auth/skill-gap/analyze', 'POST')); await loadBase() })}>Analyze my skill gap</button>{gap && <div className="gap-result"><article className="score-card"><p>READINESS FOR {gap.target_role.toUpperCase()}</p><strong>{gap.readiness_score}%</strong><Meter value={gap.readiness_score} /><span>{gap.matching_skills.length} of {gap.required_skills.length} core skills matched</span></article><SkillGroup title="Already in your toolkit" skills={gap.matching_skills} tone="good" /><SkillGroup title="Skills to develop next" skills={gap.missing_skills} tone="warn" /></div>}</>}
    {view === 'roadmap' && <><PageTitle title="Learning roadmap" text="Turn your skill gaps into a weekly, practical plan." /><div className="duration-row">{[4,8,12,16].map(weeks => <button key={weeks} className={roadmap?.weeks === weeks ? 'selected' : 'secondary'} onClick={() => action(async () => { setRoadmap(await request<Roadmap>(`/auth/roadmap/generate?weeks=${weeks}`, 'POST')); setChecked([]) })}>{weeks} weeks</button>)}</div>{roadmap && <><div className="roadmap-summary panel"><div><p className="eyebrow">{roadmap.target_role.toUpperCase()} PLAN</p><h2>{checked.length} of {roadmap.roadmap.length} weeks complete</h2></div><div><strong>{Math.round(100 * checked.length / roadmap.roadmap.length)}%</strong><Meter value={100 * checked.length / roadmap.roadmap.length} /></div></div><div className="roadmap-list">{roadmap.roadmap.map(item => { const done = checked.includes(item.week); return <article className={`roadmap-item ${done ? 'done' : ''}`} key={item.week}><button className="check" aria-label={`Mark week ${item.week} complete`} onClick={() => setChecked(old => done ? old.filter(x => x !== item.week) : [...old, item.week])}>{done ? '✓' : ''}</button><div><p className="eyebrow">WEEK {item.week} · {item.estimated_hours} HOURS</p><h3>{item.goal}</h3><ul>{item.tasks.map(task => <li key={task}>{task}</li>)}</ul><p className="milestone">Milestone: {item.milestone}</p></div></article>})}</div></>}</>}
    {view === 'practice' && <><PageTitle title="Practice questions" text="Build fluency with short, focused questions." /><button onClick={() => action(async () => setQuestions(await request<Question[]>('/auth/practice/questions')))}>Load questions</button>{questions.length ? <div className="practice-list">{questions.map(question => <article className="panel" key={question.id}><div className="section-head"><div><Chip tone="blue">{question.topic}</Chip> <Chip>{question.difficulty}</Chip></div><span className="muted">{question.type}</span></div><h3>{question.question}</h3><div className="options">{question.options.map(option => <label key={option}><input type="radio" name={question.id} checked={answers[question.id] === option} onChange={() => setAnswers(old => ({ ...old, [question.id]: option }))} />{option}</label>)}</div><button disabled={!answers[question.id]} onClick={() => action(async () => { const result = await request<{ correct: boolean; explanation: string }>(`/auth/practice/${question.id}/submit?answer=${encodeURIComponent(answers[question.id])}`, 'POST'); setPracticeResults(old => ({ ...old, [question.id]: result })) })}>Check answer</button>{practiceResults[question.id] && <p className={`answer ${practiceResults[question.id].correct ? 'correct' : 'incorrect'}`}>{practiceResults[question.id].correct ? 'Correct — ' : 'Not quite — '}{practiceResults[question.id].explanation}</p>}</article>)}</div> : <Empty text="Load questions when you’re ready for a quick practice session." />}</>}
    {view === 'interview' && <><PageTitle title="Mock interview" text="Practice a role-aware response and get immediate structure feedback." /><button onClick={() => action(async () => { setInterview(await request('/auth/interview/start', 'POST')); setInterviewFeedback(null) })}>Start interview</button>{interview && <article className="interview-card panel"><Chip tone="blue">{interview.type} · {interview.target_role}</Chip><h2>{interview.question}</h2><form onSubmit={event => { event.preventDefault(); const answer = String(new FormData(event.currentTarget).get('answer') || ''); action(async () => setInterviewFeedback(await request(`/auth/interview/evaluate?answer=${encodeURIComponent(answer)}`, 'POST'))) }}><textarea required name="answer" rows={7} placeholder="Use a specific example: context, your contribution, technologies, and outcome." /><button>Get feedback</button></form>{interviewFeedback && <div className="feedback-box"><div><strong>{interviewFeedback.overall_score}%</strong><span>overall response score</span></div><div><strong>{interviewFeedback.communication_score}%</strong><span>communication</span></div><p>{interviewFeedback.feedback}</p></div>}</article>}</>}
    {view === 'projects' && <><PageTitle title="Project recommendations" text="Build portfolio evidence around the skills your target role needs." /><button onClick={() => action(async () => { const data = await request<{ projects: Project[] }>('/auth/projects/recommendations'); setProjects(data.projects) })}>Generate project ideas</button>{projects.length ? <div className="project-grid">{projects.map(project => <article className="panel" key={project.name}><div className="section-head"><h2>{project.name}</h2><Chip tone="blue">{project.difficulty}</Chip></div><p>{project.problem_statement}</p><div className="chips">{project.skills_learned.map(skill => <Chip key={skill}>{skill}</Chip>)}</div><ol>{project.steps.map(step => <li key={step}>{step}</li>)}</ol></article>)}</div> : <Empty text="Generate ideas tailored to your role and current skill gaps." />}</>}
    {view === 'feedback' && <><PageTitle title="Career feedback" text="A concise snapshot of your current preparation and most useful next moves." /><div className="action-row"><button onClick={() => action(async () => setFeedback(await request<Feedback>('/auth/feedback/summary')))}>Generate feedback</button><button className="secondary" onClick={() => action(async () => { const data = await request<{ actions: { priority: number; action: string; minutes: number }[] }>('/auth/recommendations/today'); setToday(data.actions) })}>Plan my day</button></div>{feedback && <><article className="score-card"><p>OVERALL READINESS</p><strong>{feedback.overall_readiness}%</strong><Meter value={feedback.overall_readiness} /><span>Next milestone: {feedback.next_milestone}</span></article><div className="two-col"><SkillGroup title="Strong areas" skills={feedback.strong_areas} tone="good" /><SkillGroup title="Priority areas" skills={feedback.weak_areas} tone="warn" /></div><article className="panel"><h2>Recommended next actions</h2><ol>{feedback.immediate_actions.map(action => <li key={action}>{action}</li>)}</ol></article></>}{today.length > 0 && <article className="panel today"><h2>Today’s focused plan</h2>{today.map(item => <div key={item.priority}><Chip tone="blue">{item.minutes} min</Chip><span>{item.action}</span></div>)}</article>}</>}
  </section></div>
}

function PageTitle({ title, text }: { title: string; text: string }) { return <header className="page-title"><p className="eyebrow">CAREERAI MENTOR</p><h1>{title}</h1><p>{text}</p></header> }
function SkillGroup({ title, skills, tone }: { title: string; skills: string[]; tone: string }) { return <article className="panel skill-group"><h2>{title}</h2>{skills.length ? <div className="chips">{skills.map(skill => <Chip key={skill} tone={tone}>{tone === 'good' ? '✓ ' : '+ '}{skill}</Chip>)}</div> : <p className="muted">Nothing here yet.</p>}</article> }
export default App
